/**
 * Edge Proxy Router — Host-header reverse proxy, multi-server cluster router & Caddyfile generator.
 */

export interface HostRoute {
  host: string
  targetPort: number
  siteId: string
  nodeUrl?: string // Remote worker VPS URL if provisioned on a cluster node
}

const routes = new Map<string, HostRoute>()

export function registerRoute(host: string, targetPort: number, siteId: string, nodeUrl?: string): void {
  routes.set(host.toLowerCase(), { host, targetPort, siteId, nodeUrl })
}

export function unregisterRoute(host: string): boolean {
  return routes.delete(host.toLowerCase())
}

export function getRoute(host: string): HostRoute | undefined {
  const cleanHost = host.split(':')[0].toLowerCase()
  return routes.get(cleanHost)
}

export function getAllRoutes(): HostRoute[] {
  return Array.from(routes.values())
}

export function generateCaddyfile(): string {
  const lines: string[] = ['# Caddyfile — Generated by Instatic SaaS Multi-Server Cluster Orchestrator', '']

  for (const route of routes.values()) {
    lines.push(`${route.host} {`)
    if (route.nodeUrl) {
      // Remote worker VPS node reverse proxy
      const cleanNodeHost = route.nodeUrl.replace(/^https?:\/\//, '')
      lines.push(`  reverse_proxy ${cleanNodeHost}`)
    } else {
      // Local port reverse proxy
      lines.push(`  reverse_proxy 127.0.0.1:${route.targetPort}`)
    }
    lines.push(`}`)
    lines.push('')
  }

  return lines.join('\n')
}

interface ProxySocketData {
  targetPort: number
  targetPath: string
  cookie?: string
  origin?: string
  hostHeader: string
  protoHeader: string
  clientWs?: WebSocket
}

export function createProxyServer(proxyPort = 8080) {
  return Bun.serve<ProxySocketData>({
    port: proxyPort,
    async fetch(req, server) {
      const url = new URL(req.url)
      const hostHeader = req.headers.get('host') ?? url.hostname
      const route = getRoute(hostHeader)

      if (!route) {
        return new Response(
          `<html><body><h2>404 — Site not found or domain not registered</h2><p>Host: ${hostHeader}</p></body></html>`,
          { status: 404, headers: { 'Content-Type': 'text/html; charset=utf-8' } },
        )
      }

      // Handle WebSocket upgrade requests (e.g. Yjs real-time co-editing /admin/api/cms/site-socket)
      if (req.headers.get('upgrade')?.toLowerCase() === 'websocket') {
        const protoHeader = req.headers.get('x-forwarded-proto') ?? url.protocol.replace(':', '')
        const upgraded = server.upgrade(req, {
          data: {
            targetPort: route.targetPort,
            targetPath: url.pathname + url.search,
            cookie: req.headers.get('cookie') ?? undefined,
            origin: req.headers.get('origin') ?? undefined,
            hostHeader,
            protoHeader,
          },
        })
        if (upgraded) return undefined
      }

      // Determine proxy destination: Remote Cluster Node OR Local Port
      let targetUrl: URL
      if (route.nodeUrl) {
        targetUrl = new URL(url.pathname + url.search, route.nodeUrl)
      } else {
        targetUrl = new URL(req.url)
        targetUrl.hostname = '127.0.0.1'
        targetUrl.port = String(route.targetPort)
      }

      const headers = new Headers(req.headers)
      const protoHeader = req.headers.get('x-forwarded-proto') ?? url.protocol.replace(':', '')
      headers.set('X-Forwarded-Host', hostHeader)
      headers.set('X-Forwarded-Proto', protoHeader)

      try {
        const response = await fetch(targetUrl.toString(), {
          method: req.method,
          headers,
          body: req.method !== 'GET' && req.method !== 'HEAD' ? await req.arrayBuffer() : undefined,
          redirect: 'manual',
        })

        // Fix ERR_CONTENT_DECODING_FAILED:
        // Bun's fetch() automatically decodes compressed bodies (brotli/gzip) in proxy requests
        // but preserves original Content-Encoding headers. Removing Content-Encoding prevents browser decoding errors.
        const resHeaders = new Headers(response.headers)
        resHeaders.delete('content-encoding')
        resHeaders.delete('content-length')

        return new Response(response.body, {
          status: response.status,
          statusText: response.statusText,
          headers: resHeaders,
        })
      } catch {
        return new Response(`502 — Site instance for ${hostHeader} is not reachable`, {
          status: 502,
          headers: { 'Content-Type': 'text/plain; charset=utf-8' },
        })
      }
    },
    websocket: {
      open(ws) {
        const { targetPort, targetPath, cookie, origin, hostHeader, protoHeader } = ws.data
        const targetWsUrl = `ws://127.0.0.1:${targetPort}${targetPath}`

        const wsHeaders: Record<string, string> = {
          'X-Forwarded-Host': hostHeader,
          'X-Forwarded-Proto': protoHeader,
        }
        if (cookie) wsHeaders['cookie'] = cookie
        if (origin) wsHeaders['origin'] = origin

        try {
          const targetWs = new WebSocket(targetWsUrl, {
            headers: wsHeaders,
          } as unknown as string[])

          ws.data.clientWs = targetWs

          targetWs.addEventListener('message', (event) => {
            try {
              ws.send(event.data)
            } catch {
              // Socket closed
            }
          })

          targetWs.addEventListener('close', () => {
            try {
              ws.close()
            } catch {
              // Socket closed
            }
          })

          targetWs.addEventListener('error', () => {
            try {
              ws.close()
            } catch {
              // Socket closed
            }
          })
        } catch {
          ws.close()
        }
      },
      message(ws, message) {
        if (ws.data.clientWs && ws.data.clientWs.readyState === WebSocket.OPEN) {
          ws.data.clientWs.send(message)
        }
      },
      close(ws) {
        if (ws.data.clientWs) {
          try {
            ws.data.clientWs.close()
          } catch {
            // Socket closed
          }
        }
      },
    },
  })
}
