/**
 * Edge Proxy Router — Host-header reverse proxy, multi-server cluster router & Caddyfile generator.
 */

export interface HostRoute {
  host: string
  targetPort: number
  siteId: string
  nodeUrl?: string // Remote worker VPS URL if provisioned on a cluster node
}

const routes = new Map<string, HostRoute>()

export function registerRoute(host: string, targetPort: number, siteId: string, nodeUrl?: string): void {
  routes.set(host.toLowerCase(), { host, targetPort, siteId, nodeUrl })
}

export function unregisterRoute(host: string): boolean {
  return routes.delete(host.toLowerCase())
}

export function getRoute(host: string): HostRoute | undefined {
  const cleanHost = host.split(':')[0].toLowerCase()
  return routes.get(cleanHost)
}

export function getAllRoutes(): HostRoute[] {
  return Array.from(routes.values())
}

export function generateCaddyfile(): string {
  const lines: string[] = ['# Caddyfile — Generated by Instatic SaaS Multi-Server Cluster Orchestrator', '']

  for (const route of routes.values()) {
    lines.push(`${route.host} {`)
    if (route.nodeUrl) {
      // Remote worker VPS node reverse proxy
      const cleanNodeHost = route.nodeUrl.replace(/^https?:\/\//, '')
      lines.push(`  reverse_proxy ${cleanNodeHost}`)
    } else {
      // Local port reverse proxy
      lines.push(`  reverse_proxy 127.0.0.1:${route.targetPort}`)
    }
    lines.push(`}`)
    lines.push('')
  }

  return lines.join('\n')
}

export function createProxyServer(proxyPort = 8080) {
  return Bun.serve({
    port: proxyPort,
    async fetch(req) {
      const url = new URL(req.url)
      const hostHeader = req.headers.get('host') ?? url.hostname
      const route = getRoute(hostHeader)

      if (!route) {
        return new Response(
          `<html><body><h2>404 — Site not found or domain not registered</h2><p>Host: ${hostHeader}</p></body></html>`,
          { status: 404, headers: { 'Content-Type': 'text/html; charset=utf-8' } },
        )
      }

      // Determine proxy destination: Remote Cluster Node OR Local Port
      let targetUrl: URL
      if (route.nodeUrl) {
        targetUrl = new URL(url.pathname + url.search, route.nodeUrl)
      } else {
        targetUrl = new URL(req.url)
        targetUrl.hostname = '127.0.0.1'
        targetUrl.port = String(route.targetPort)
      }

      const headers = new Headers(req.headers)
      headers.set('X-Forwarded-Host', hostHeader)
      headers.set('X-Forwarded-Proto', url.protocol.replace(':', ''))

      try {
        return await fetch(targetUrl.toString(), {
          method: req.method,
          headers,
          body: req.method !== 'GET' && req.method !== 'HEAD' ? await req.arrayBuffer() : undefined,
          redirect: 'manual',
        })
      } catch {
        return new Response(`502 — Site instance for ${hostHeader} is not reachable`, {
          status: 502,
          headers: { 'Content-Type': 'text/plain; charset=utf-8' },
        })
      }
    },
  })
}
